# Generated by Django 6.0.3 on 2026-03-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='descipçion',
            new_name='descripcion',
        ),
    ]
