# Generated by Django 6.0.3 on 2026-04-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_descipçion_equipo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
