# Generated by Django 6.0.3 on 2026-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_equipo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Consumible')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Consumible',
                'verbose_name_plural': 'Consumibles',
                'db_table': 'consumible',
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estacion',
            field=models.IntegerField(verbose_name='Estacion de trabajo'),
        ),
    ]
