# Generated by Django 6.0.3 on 2026-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_consumible_alter_equipo_estacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='date_reg',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='identificador',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='identificador'),
        ),
    ]
