# Generated by Django 6.0.3 on 2026-03-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='SalaPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('date', models.DateField(verbose_name='Fecha de uso')),
                ('hour', models.TimeField(verbose_name='Hora de inicio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salapcs.profesor')),
            ],
            options={
                'verbose_name': 'SalaPC',
                'verbose_name_plural': 'SalasPC',
                'db_table': 'salapc',
            },
        ),
    ]
