# Generated by Django 6.0.3 on 2026-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='permissions',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('profesor', 'Profesor')], max_length=255, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo'),
        ),
    ]
