# Generated by Django 6.0.3 on 2026-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_perfil_permissions_alter_perfil_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='permissions',
            field=models.CharField(choices=[('admin', 'Admin'), ('profesor', 'Profesor')], max_length=255, verbose_name='Permissions'),
        ),
    ]
