# Generated by Django 6.0.3 on 2026-03-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dispositivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='identificador')),
                ('estacion', models.IntegerField(unique=True, verbose_name='Estacion de trabajo')),
                ('descipçion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('date_reg', models.DateField(verbose_name='Fecha de ingreso')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
            },
        ),
    ]
